### ISSUE TITLE
4.30 8:30 추가 필요한 api 

### ISSUE THREAD

**Issue by seorang42** [SurBear-Team/surbear-frontend#25]
1. 등록한 설문조사 내역 조회 api 필요
- /role/participating과 동일한 사용자 입장 api가 필요

2. 회원정보 수정 api 필요
- 닉네임, 나이대 수정용 post api 필요

추가 후 댓글 남겨주세요

**Comment by seorang42** [comment]
+ 프로필에서 등록한/참여한 설문조사 개수 필요 ("/member" api)

**Comment by jickDo** [comment]
> 1. 등록한 설문조사 내역 조회 api 필요
> 
> * /role/participating과 동일한 사용자 입장 api가 필요
> 
> 2. 회원정보 수정 api 필요
> 
> * 닉네임, 나이대 수정용 post api 필요
> 
> 추가 후 댓글 남겨주세요

`Q1. 1번이 피그마 기준 '내 설문조사 내역' 뷰에서 위 버전, 아래 버전중에 아래버전으로 구현하는건가요? `
`Q3. 3번이 어디에서 쓸 부분인지와, 등록한/ 참여한 설문조사가 삭제된 설문포함인가요? 아니면 DELETION, FORCED_DELETION 제외인가요?`

**Comment by seorang42** [comment]
> > 1. 등록한 설문조사 내역 조회 api 필요
> > 
> > 
> > * /role/participating과 동일한 사용자 입장 api가 필요
> > 
> > 
> > 2. 회원정보 수정 api 필요
> > 
> > 
> > * 닉네임, 나이대 수정용 post api 필요
> > 
> > 추가 후 댓글 남겨주세요
> 
> `Q1. 1번이 피그마 기준 '내 설문조사 내역' 뷰에서 위 버전, 아래 버전중에 아래버전으로 구현하는건가요? ` `Q3. 3번이 어디에서 쓸 부분인지와, 등록한/ 참여한 설문조사가 삭제된 설문포함인가요? 아니면 DELETION, FORCED_DELETION 제외인가요?`

A1. 아래 버전입니다.
A3. 내 프로필 메인 화면의 카드에 들어갈 내용들이며, 내역 보기 버튼을 눌렀을 때 삭제/강제삭제된 설문조사 내역도 보여주기 때문에 해당 설문도 계산해서 숫자에 포함시켜야 할 것 같습니다

**Comment by jickDo** [comment]
구현되었고 스웨거 한번 확인해주세요
